services:
  db:
    container_name: 'todo_db'
    image: postgres:16
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    networks:
      - my_network
  backend:
    container_name: 'todo_back'
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - my_network
    ports:
      - "8000:8000"

  frontend:
    container_name: 'todo_front'
    build:
      context: .
      dockerfile: frontend/Dockerfile
    networks:
      - my_network
    ports:
      - "4173:4173"


volumes:
  pgdata:


networks:
  my_network:
    external: true
